[env]
MACOSX_DEPLOYMENT_TARGET = { value = "11.0", force = true }
CMAKE_OSX_DEPLOYMENT_TARGET = { value = "11.0", force = true }

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-stdlib=libc++", "-C", "link-arg=-mmacosx-version-min=11.0"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-stdlib=libc++", "-C", "link-arg=-mmacosx-version-min=11.0"]

